<?php

namespace InfoCampusBundle\Repository;

/**
 * AbonnesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnesRepository extends \Doctrine\ORM\EntityRepository
{
}
