<?php

namespace InfoCampusBundle\Repository;

/**
 * AbonnesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnesRepository extends \Doctrine\ORM\EntityRepository
{

//    public function getAbonnesBy($niveau, $faculte)
//    {
//
//        $query = $this->createQueryBuilder('a')
//            ->where('a.niveau='.$niveau)
//            ->andWhere('a.faculte ='.$faculte)
//            ->getQuery();
//        $abonnes = $query->getResult();
//        return $abonnes;
//    }
}
