<?php

namespace InfoCampusBundle\Repository;

/**
 * FacultesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacultesRepository extends \Doctrine\ORM\EntityRepository
{
}
