<?php

namespace InfoCampusBundle\Repository;

/**
 * StructuresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StructuresRepository extends \Doctrine\ORM\EntityRepository
{
}
